name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Primeiro passo
        run: echo hello world!

      - name: Segundo Passo
        run: echo $(ls)

      - name: Terceiro passo
        run: echo $(pwd)